# -*- coding: utf-8 -*-
"""mongo_upload.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nRrvFjvVfQ4O40f5qJJJsbnkcIHe5aGF
"""

import logging

# Set up logging to a file
logging.basicConfig(
    filename="mongo_upload.log",
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    force=True
)

logging.info("Mongo upload notebook started")
print("Logging set up successfully.")

!pip -q install pymongo[srv]

import pandas as pd
import csv
from pymongo import MongoClient
from getpass import getpass

try:
    # Path to cleaned clinical trials data
    cleaned_path = "/content/clinical_trials_cleaned.csv"

    # Load cleaned CSV with a more tolerant parser
    df = pd.read_csv(
        cleaned_path,
        engine="python",
        on_bad_lines="skip",
        quoting=csv.QUOTE_MINIMAL
    )

    print("Loaded cleaned data:", df.shape)
    logging.info(f"Cleaned data loaded successfully with shape {df.shape}")
    display(df.head())

except Exception as e:
    print("Error loading cleaned data:", e)
    logging.error(f"Cleaned data loading failed: {e}")
    raise

# Helper
# Function to safely replace missing pandas values with None before MongoDB upload
def safe_value(x):
    if pd.isna(x):
        return None
    return x

try:
    # Function to safely replace missing pandas values with None before MongoDB upload
    def safe_value(x):
        if pd.isna(x):
            return None
        return x

    # Build nested MongoDB documents
    records = []

    for _, row in df.iterrows():
        conditions = []
        if pd.notna(row.get("Conditions")) and str(row.get("Conditions")).strip() != "":
            conditions = [c.strip() for c in str(row["Conditions"]).split(",") if c.strip()]

        interventions = []
        if pd.notna(row.get("Interventions")) and str(row.get("Interventions")).strip() != "":
            interventions = [i.strip() for i in str(row["Interventions"]).split(",") if i.strip()]

        doc = {
            "trial_id": int(row["trial_id"]) if pd.notna(row.get("trial_id")) else None,
            "brief_title": safe_value(row.get("Brief Title")),
            "full_title": safe_value(row.get("Full Title")),
            "overall_status": safe_value(row.get("Overall Status")),
            "study_type": safe_value(row.get("Study Type")),
            "phases": safe_value(row.get("Phases")),
            "primary_purpose": safe_value(row.get("Primary Purpose")),
            "start_date": safe_value(row.get("Start Date")),
            "standard_age": safe_value(row.get("Standard Age")),
            "outcome_measure": safe_value(row.get("Outcome Measure")),
            "medical_subject_headings": safe_value(row.get("Medical Subject Headings")),
            "success": int(row["success"]) if pd.notna(row.get("success")) else None,
            "organization": {
                "organization_full_name": safe_value(row.get("Organization Full Name")),
                "organization_class": safe_value(row.get("Organization Class")),
                "responsible_party": safe_value(row.get("Responsible Party"))
            },
            "conditions": conditions,
            "interventions": {
                "names": interventions,
                "description": safe_value(row.get("Intervention Description"))
            }
        }

        records.append(doc)

    print("Documents prepared:", len(records))
    logging.info(f"Prepared {len(records)} MongoDB documents")

    records[0] if records else None

except Exception as e:
    print("Error preparing MongoDB documents:", e)
    logging.error(f"Document preparation failed: {e}")
    raise

try:
    # Prompt user for credentials securely
    username = input("Enter your MongoDB username: ")
    password = getpass("Enter your MongoDB password: ")

    # Create MongoDB connection string
    uri = f"mongodb+srv://{username}:{password}@cluster1.ecpqpus.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1"

    # Connect to MongoDB Atlas with timeout settings for stability
    client = MongoClient(
        uri,
        serverSelectionTimeoutMS=30000,
        connectTimeoutMS=30000,
        socketTimeoutMS=30000,
        retryWrites=True
    )

    # Test connection
    client.admin.command("ping")
    print("Connected successfully.")
    logging.info("Connected to MongoDB successfully")

except Exception as e:
    print("Error connecting to MongoDB:", e)
    logging.error(f"MongoDB connection failed: {e}")
    raise

try:
    # Select database and collection
    db = client["clinical_trials_project"]
    collection = db["clinical_trials"]

    print("Database:", db.name)
    print("Collection:", collection.name)
    logging.info("Database and collection selected successfully")

except Exception as e:
    print("Error selecting database or collection:", e)
    logging.error(f"Database/collection selection failed: {e}")
    raise

try:
    # Insert records in smaller batches to make upload more stable
    batch_size = 1000

    for i in range(0, len(records), batch_size):
        batch = records[i:i + batch_size]
        collection.insert_many(batch)
        print(f"Inserted {min(i + batch_size, len(records))} / {len(records)}")
        logging.info(f"Inserted {min(i + batch_size, len(records))} / {len(records)} documents")

    print("Upload complete.")
    logging.info("MongoDB upload completed successfully")

except Exception as e:
    print("Error uploading documents:", e)
    logging.error(f"MongoDB upload failed: {e}")
    raise

try:
    # Verify upload by checking document count and previewing one document
    print("Document count in MongoDB:", collection.count_documents({}))
    logging.info(f"Final MongoDB document count: {collection.count_documents({})}")

    sample_doc = collection.find_one()
    sample_doc

except Exception as e:
    print("Error verifying upload:", e)
    logging.error(f"Upload verification failed: {e}")
    raise

logging.info("Mongo upload notebook completed successfully")
print("Mongo upload complete. Log saved to mongo_upload.log")